# Generated by Django 4.2.19 on 2026-05-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_extend_experiment_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentartifact',
            options={'ordering': ['artifact_type', 'id'], 'verbose_name': '实验产物', 'verbose_name_plural': '实验产物'},
        ),
        migrations.AlterModelOptions(
            name='experimentrun',
            options={'ordering': ['-created_at'], 'verbose_name': '实验记录', 'verbose_name_plural': '实验记录'},
        ),
        migrations.AlterField(
            model_name='experimentartifact',
            name='artifact_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('image', '图像'), ('report', '报告'), ('other', '其他')], default='other', max_length=16, verbose_name='产物类型'),
        ),
        migrations.AlterField(
            model_name='experimentartifact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='experimentartifact',
            name='label',
            field=models.CharField(max_length=120, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='experimentartifact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='experimentartifact',
            name='relative_path',
            field=models.CharField(max_length=255, verbose_name='相对路径'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='command',
            field=models.TextField(blank=True, verbose_name='命令'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='配置'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='dataset',
            field=models.CharField(blank=True, max_length=32, verbose_name='数据集'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='运行名称'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='result_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='结果摘要'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='status',
            field=models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('succeeded', '已完成'), ('failed', '失败'), ('aborted', '已中止')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='stdout_log',
            field=models.TextField(blank=True, verbose_name='标准输出日志'),
        ),
    ]
